### ISSUE TITLE
remove method having trouble removing by string representation of _id

### ISSUE THREAD

**Issue by wolfchimneyrock** [jeroenooms/mongolite#12]
I am working through the MongoDB university course 101P homework and HW 2.2 requires removing documents from a collection based on _id.  with a string representation of the document's _id field in R passed to the driver thus: 

```r
doc = m$find('{}','{"_id":1}')
for (id in unlist(doc)) m$remove(sprintf('{"_id":"%s"}',id))
m$count()
```

results in a failure to remove the documents from the database.  I believe it has no way of correlating a string passed to it in the query with the objectID type in mongo?

**Comment by jeroenooms** [comment]
You need to use the `"$oid"` notation. For example:

```r
m$remove('{ "_id" : { "$oid" : "4d512b45cc9374271b02ec4f" } }')
```

**Comment by wolfchimneyrock** [comment]
Thanks... If that were in the documentation it would save a lot of
headache, since it seems there is no consensus between drivers on how to
handle objectids; explicitly describing how your particular driver handles
them seems reasonable.

**Comment by jeroenooms** [comment]
Good point. Do you want to help with creating a wiki FAQ to list such information? https://github.com/jeroenooms/mongolite/wiki/FAQ

**Comment by wolfchimneyrock** [comment]
yes, I can create a wiki.  I assume the other issues are also prime meat
for FAQ entries?

**Comment by jeroenooms** [comment]
Yes, anything you run into and that might be useful to other users you can post in the wiki :)
