### ISSUE TITLE
Any support for iterating over a cursor

### ISSUE THREAD

**Issue by wolfchimneyrock** [jeroenooms/mongolite#13]
Is there functionality to retrieve a query cursor from the database and iterator over it?  I see nothing in the documentation about it

**Comment by jeroenooms** [comment]
It's in the implementation obviously but the user interface has been abstracted. To incrementally process data you can specify a callback function using the `handler` argument in e.g. `m$find()`.

**Comment by jeroenooms** [comment]
Does that work for you?

**Comment by wolfchimneyrock** [comment]
I will try it out when i get my head wrapped around the idea.  I take it
the handler only has one parameter, the pagesized dataframe of the
tablerows?  so if I want to access variables in the scope outside I have to
use an inline function?  can i make it use a data.table instead of
data.frame by default?

**Comment by jeroenooms** [comment]
Your handler function can do whatever you do in R, there is no NSE or anything. So if your handler has local variables in it's scope those will be available, and you can use `as.data.table` in your function.

**Comment by jeroenooms** [comment]
I have also added experimental support for manually iterating with `m$finditer`.

**Comment by jeroenooms** [comment]
This is on CRAN now. See this announcement: https://www.opencpu.org/posts/mongolite-release-0-5/

**Comment by wolfchimneyrock** [comment]
ah very nice!  I have been distracted from my project for the last month
but I will dig back into it.
