### ISSUE TITLE
Error: Class 'mongo' has no field XXX'

### ISSUE THREAD

**Issue by dkalisch** [jeroenooms/mongolite#14]
I am trying out the mogolite library on a ubuntu 15.04 with RR0-3-2-0. I get the package installed and most of the commands from the tutorial work.
However, I get error messages with the following commands:

tbl <- m$mapreduce(
+     map = "function(){emit({cut:this.cut, color:this.color}, 1)}",
+     reduce = "function(id, counts){return Array.sum(counts)}"
+ )
Error: Class 'mongo' has no field 'map reduce'

allflights <- m$find(sort='{"distance":-1}')
Error in m$find(sort = "{\"distance\":-1}") : 
  unused argument (sort = "{\"distance\":-1}")

m$distinct("carrier", '{"distance":{"$gt":3000}}')
Error: Class 'mongo' has no field 'distinct'

m$export(file(dump), bson = TRUE)
Error: Class 'mongo' has no field 'export'

m$import(file(dump), bson = TRUE)
Error: Class 'mongo' has no field 'import'

Any idea why and how i can solve this?
Thanks for your help.

**Comment by jeroenooms** [comment]
Looks like you have an old version of mongolite? Try updating:

```
install.packages("mongolite")
```

**Comment by dkalisch** [comment]
Jeroen,

I installed now mongolite from github. Now it works, Analytics R had an older version in their repository... Thanks.
