### ISSUE TITLE
More flexible and convenient streaming

### ISSUE THREAD

**Issue by lawremi** [jeroenooms/mongolite#16]
Currently, `$find()` coerces to `data.frame` prior to calling `handler`. This makes the assumption that the data fit nicely in a table. While we all like R `data.frame`s, Mongo, of course, makes no such assumptions. 

It would also be more convenient if the streamer optionally saved the result of each reduction (like the default handler), and the results would be later collapsed by another function. A simple contract would be: if a `collapse` function is specified, save the result of each iteration, and pass all of them as a list to `collapse`; otherwise, the behavior remains as it is now.

**Comment by jeroenooms** [comment]
Are you aware of iterate?https://www.opencpu.org/posts/mongolite-release-0-5/

**Comment by lawremi** [comment]
Sure, but I thought the batch processing would offer better performance.

**Comment by lawremi** [comment]
I guess at a minimum, it would be nice to have an option to just return the data as a list.

**Comment by jeroenooms** [comment]
That is exactly what iterate does

**Comment by lawremi** [comment]
Ok, the functionality of `iterate` was not clear from the man page. From the blog post, I see that batch processing is possible, so we have the "flexible" part, but what about the "convenient"? Efficient iteration in R can be painful. This motivated the suggestion of a high-level option for just returning a list, which would satisfy my immediate use case.

**Comment by jeroenooms** [comment]
The `$batch` method in the iterator does this.
