### ISSUE TITLE
Date type

### ISSUE THREAD

**Issue by cronacronis** [jeroenooms/mongolite#18]
Thx for awesome performance package.

There is no support for `Date` type. `Date` is returned as `character`.
So far it convertes `POSIXct` successfuly. It there a plan to support `Date` as well?

_P.S._
_Currently, when you `$import` and `$find` why is it converted to JSON?_

**Comment by DavidSichau** [comment]
It would also be nice to import Date objects to mongodb, they are all converted to Strings

**Comment by jeroenooms** [comment]
MongoDB does not have a notion of a "date". There is only datetime. So you have to convert your dates to POSIXct in R using `as.POSIXct(dates)` before inserting.
