### ISSUE TITLE
Option to use data.table as storage container instead of data.frame

### ISSUE THREAD

**Issue by wllmtrng** [jeroenooms/mongolite#19]
data.tables provide the ability to change fields on the object without implicitly making a copy of the original data.frame. For bigger datasets this would speed up performance for data munging tasks.

**Comment by jeroenooms** [comment]
How is this related to mongodb? You can use data table objects where instead of data frame?

**Comment by wllmtrng** [comment]
```
> my_collection = mongo(collection="foo", db="examples")
> x = my_collection$find()
```

x is a data frame at this point. Now, suppose x contains 100,000 rows. Adding a new column or modifying an existing value to x will cause R to make a copy of the data frame.

```
> tracemem(x)
[1] "<0x10c2b43f0>"
> x["new"] = c(1,2,3,4,5)
tracemem[0x10c2b43f0 -> 0x121698a70]: 
tracemem[0x121698a70 -> 0x121337e98]: [<-.data.frame [<- 
```

With data.tables we can take advantage of the := operator which modifies the existing object:

```
> dt = data.table(c(1,2,3), c(4,5,6))
> dt
   V1 V2
1:  1  4
2:  2  5
3:  3  6
> tracemem(dt)
[1] "<0x10f805c70>"
> dt[,"new":= c(7,8,9)]
> tracemem(dt)
[1] "<0x10f805c70>"
> dt
   V1 V2 new
1:  1  4   7
2:  2  5   8
3:  3  6   9
```

Thoughts?

**Comment by jeroenooms** [comment]
I think the easiest approach is if the user converts the data frame to data table. I don't think it is useful to do this in mongolite. Basically it would to exactly the same thing: first construct the data frame structure and then coerse that to data.table.

**Comment by wllmtrng** [comment]
After some digging I found the function to do this by reference and not by copy:
http://www.rdocumentation.org/packages/data.table/functions/setDT

Thanks for the discussion.

**Comment by jeroenooms** [comment]
Great, good to know. Thanks.
