### ISSUE TITLE
Representation of _ID inconsistenc

### ISSUE THREAD

**Issue by oroant** [jeroenooms/mongolite#20]
Some strange behavior around representation of _id as described below: 

DocId = "4fd39aa38eb7c8105d8d8114"
qry = sprintf('{"_id":{"$oid":"%s"}}',DocId)
m$find(qry, fields = '{"keywords":1, "lead_paragraph":1, "organization":1}' ) 
Imported 0 records. Simplifying into dataframe...

But following results in 1 record: 
m$find(query = '{\"_id\": "4fd39aa38eb7c8105d8d8114"}', 
       fields = '{"keywords":1, "lead_paragraph":1, "organization":1}')
Imported 1 records. Simplifying into dataframe...

Using mongo shell version 3.07, R Version 3.2.2, RStudio Server Version 0.99.484 every thing on Ubuntu 14.04.3 LTS

**Comment by jeroenooms** [comment]
The `$oid` operator seems to work here. Simple example:

```r
library(mongolite)
m <- mongo("iris")
m$insert(iris)
mydata <- m$find(fields = '{}', limit = 10)
rec_id <- mydata[[1, "_id"]]
id_str <- paste(rec_id, collapse = "")

# Create a query
query <- sprintf('{\"_id\": {"$oid":"%s"}}', id_str)
cat(query)
m$find(query)
```

**Comment by jeroenooms** [comment]
Assuming this is solved. Please post a new issue if this is not working.
