### ISSUE TITLE
SSL Example

### ISSUE THREAD

**Issue by chasset** [jeroenooms/mongolite#21]
Hello,
Can you give explicit example using SSL to connect to mongodb? May be with a parameter passing the public certificate?
Many thanks,
Pierre-Olivier

**Comment by jeroenooms** [comment]
Unfortunately I don't have access to any SSL servers. You should be able to pass SSL options in the `mongodb://` url using the [standard syntax](https://docs.mongodb.org/v3.0/reference/connection-string/). If you need additional options we can easily add those.

**Comment by jeroenooms** [comment]
Can you let me know if you get things to work? This is valuable feedback.

**Comment by chasset** [comment]
yes. as soon as possible

**Comment by jeroenooms** [comment]
Please continue discussion at https://github.com/jeroenooms/mongolite/issues/30.
