### ISSUE TITLE
Is there a way to avoid simplifying into data frame?

### ISSUE THREAD

**Issue by renkun-ken** [jeroenooms/mongolite#24]
In some cases, the result is highly volatile in terms of document structure. Is there a way to let `find()` avoid simplifying the results into a data frame?

**Comment by jeroenooms** [comment]
You can use the `$iter()` method to pull records without simplification: https://www.opencpu.org/posts/mongolite-release-0-5/

**Comment by renkun-ken** [comment]
Thanks!
