### ISSUE TITLE
shinyapps.io deployment

### ISSUE THREAD

**Issue by DimitriF** [jeroenooms/mongolite#25]
Hello,

I do not manage to deploy an application with the mongolite package, the deployment is stuck when it comes to build the package, 
I am building with rsconnect version 0.4.1.9.
Here is the log:
```r
[2015-12-31T16:06:37.179563073+0000] Building R package: mongolite (0.7)
/mnt/packages/build /mnt
* installing to library ‘/usr/local/lib/R/site-library’
* installing *source* package ‘mongolite’ ...
** package ‘mongolite’ successfully unpacked and MD5 sums checked
Found pkg-config cflags and libs!
Using PKG_CFLAGS= 
Using PKG_LIBS=-lsasl2 -lssl -lcrypto  
------------------------- ANTICONF ERROR ---------------------------
Configuration failed because openssl/sasl was not found. Try installing:
 * deb: libssl-dev, libsasl2-dev (Debian, Ubuntu, etc)
 * rpm: openssl-devel, cyrus-sasl-devel (Fedora, CentOS, RHEL)
 * csw: libssl_dev, sasl_dev (Solaris)
 * brew: openssl (Mac OSX)
If openssl is already installed, check that 'pkg-config' is in your
PATH and PKG_CONFIG_PATH contains a openssl.pc file. If pkg-config
is unavailable you can set INCLUDE_DIR and LIB_DIR manually via:
R CMD INSTALL --configure-vars='INCLUDE_DIR=... LIB_DIR=...'
--------------------------------------------------------------------
ERROR: configuration failed for package ‘mongolite’
* removing ‘/usr/local/lib/R/site-library/mongolite’
################################# End Task Log ################################# 
Error: Unhandled Exception: Child Task 123656666 failed: Error building image: Error building mongolite (0.7). Build exited with non-zero status: 1
```
Any hints?
Thanks in advance
Dimitri

**Comment by jeroenooms** [comment]
You need to install `openssl` and `sasl` on your server, like it says.

**Comment by DimitriF** [comment]
should have said it before, I am using shinyapps.io, I do not have access to the server side. openssl is installed on my machine (OS X 10.10.3 (Yosemite)), but no success to deploy it, I should may be contact the people from RStudio?

**Comment by jeroenooms** [comment]
Hmmm interesting. I'm not sure what OS the shinyapps server runs, but they would need to have `libssl-dev` and `libsasl2-dev` on the system. I don't have too much experience with shiny, but could you should me the code I would need to use to deploy, so I can try to reproduce the problem?

**Comment by DimitriF** [comment]
The strange thing is that [here](http://shiny.rstudio.com/articles/persistent-data-storage.html), they recommand your package for easy storage of data through shinyapps, it seems that they didn't think about shinyapps.io.

sessionInfo() from a running shinyapps on their server give:
R version 3.2.2 (2015-08-14)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu precise (12.04.4 LTS)

by calling the terminal with an Ace editor from the same running shinyapps:
```r
system("dpkg-query -l 'libssl-dev'",intern=T)
```
```r
[1] "Desired=Unknown/Install/Remove/Purge/Hold"                                                                                                              
[2] "| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend"                                                                         
[3] "|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)"                                                                                             
[4] "||/ Name                             Version                             Description"                                                                   
[5] "+++-================================-===================================-=============================================================================="
[6] "ii  libssl-dev                       1.0.1-4ubuntu5.22                   SSL development libraries, header files and documentation"        
```

But libsasl2-dev looks missing:
```r
system("dpkg-query -l 'libsasl2-dev",intern=T)
```
```r
character(0)
attr(,"status")
[1] 1
```

For reproductible example, it will be simpler to create a new project from RStudio, new directory and select to create a shiny application. Then add in ui.R file or server.R
```r
library(mongolite)
```
Create an account on shinyapps.io, sign in, look for **account**, create a token, then run:
```r
shinyapps::setAccountInfo(name=*YOUR ACCOUNT NAME*, token=*YOUR TOKEN*, secret=*YOUR SECRET*)
rsconnect::deployApp(*YOUR PATH*,account=*YOUR ACCOUNT NAME*,appName="test")
```
with the mongolite library, it fail and without it work

**Comment by jeroenooms** [comment]
It looks like they forgot to install `libsasl2-dev` on the shinyapps.io server, which is required by `mongolite`. Maybe @jjallaire or @jcheng5 can suggest who can help us to get this installed?

**Comment by DimitriF** [comment]
Ok, so the problem comes from the server side, not the package side.
I open an issue [in the rsconnect repo](https://github.com/rstudio/rsconnect/issues)
Thanks for your help

**Comment by DimitriF** [comment]
They install libsas12-dev on the shinyapps.io server
thanks
