### ISSUE TITLE
Date saved as string

### ISSUE THREAD

**Issue by georgeu2000** [jeroenooms/mongolite#26]
I have a zoo object with a date index:

```
date = index(aapl[1])  
date
## [1] "1991-01-02"
class(date)
## [1] "Date"
df = data.frame(date, close, updated_at)
mongo$insert(df)
```

When I look in the Mongo DB, I see:

```
  "date": "1991-01-02",
```

So, it seems that the date is saved as a string instead of a date object.

**Comment by jeroenooms** [comment]
Mongo does not have a plain date type. It does have a timestamp. Try converting your date to a POSIX timestamp and insert it then:

```r
times <- as.POSIXct(date)
```
