### ISSUE TITLE
Citation wrong?

### ISSUE THREAD

**Issue by Robinlovelace** [jeroenooms/mongolite#28]
Just trying to cite this and I get "The jsonlite Package: A Practical and Consistent Mapping Between JSON Data and R Objects". Surely it should refer to mongolite, non?

**Comment by jeroenooms** [comment]
Yes it does, a new revision of the paper will mention mongo as an alternative storage back-end for serializing to json.

**Comment by Robinlovelace** [comment]
Ah OK - any info when the paper will be updated? Got ~1 month before my stuff needs to be submitted - at the minute I've not referenced it.

**Comment by jeroenooms** [comment]
You can still reference it... mongolite just wraps around jsonlite and then inserts the output in the db. The mapping between r objects and json in the mongo db is the one described in the paper.

**Comment by Robinlovelace** [comment]
:+1: ta for the explanation
