### ISSUE TITLE
storing doubles via m$insert -> precision loss

### ISSUE THREAD

**Issue by fred777** [jeroenooms/mongolite#29]
I'm running MongoDB 3.2.3 on Ubuntu 14.04 x85_64 and connect via R 3.2.3 on Windows 7 x64.

Double numbers seem to get truncated by mongolite and I have no clue why. With rmongodb package I did not face any truncation.

Code to reproduce:

```
my_data=data.frame(rnorm(100L))
m=mongo(collection="test")
if(m$count()>0) m$drop()
m$insert(my_data)
x=m$find()
all(my_data==x)         # I'm getting FALSE here, expected TRUE
max(abs(my_data-x)) # I'm getting something around 1e-10 here, expected 0
```

As far as I can tell, the culprit lies in m$insert. Writing the data with rmongodb and reading back with mongolite does not suffer from truncation.

**Comment by jeroenooms** [comment]
Yes mongolite converts the data to json before inserting which might lead to loss of precision. Is this problematic in your use case?

**Comment by fred777** [comment]
As I want to use MongoDB for number crunching - yes, might be problematic.

Scanning through the source code, I did not realize that you convert to JSON first... Where does that magic happen?

**Comment by jeroenooms** [comment]
Here: https://github.com/jeroenooms/mongolite/blob/master/R/stream.R#L6-L10. As a workaround we could just raise the number of digits that will be printed when converting to json.

**Comment by fred777** [comment]
Ah, yes. Thanks! There where so many *_bson_* functions everywhere that I missed that.

So, in the end, converting to JSON and using mongoc to create BSON from JSON made implementation easier...

https://github.com/jeroenooms/mongolite/blob/60a68e9c7da7270a3a3cdba11fc810983052e90f/src/collection.c#L95

I can live with that for the moment.

Now, it's also clear to me why rmongodb is more than twice as fast uppon insertion ;-)

**Comment by jeroenooms** [comment]
Yes exactly. We could reimplement a function to convert dataframes directly to bson, however making it behave the same as the asJSON.data.frame mapping from jsonlite is actually very difficult and a lot of work. So this is kind of a shortcut, for now :-)

**Comment by scalastic** [comment]
As a workaround, would it be possible that you read an `options(digits = xx)` to specify `digits` value passed to https://github.com/jeroenooms/mongolite/blob/master/R/stream.R#L20-L20 ?

**Comment by jeroenooms** [comment]
This should be fixed now.
