### ISSUE TITLE
Could mongo$find() have an argument to return list?

### ISSUE THREAD

**Issue by durtal** [jeroenooms/mongolite#3]
First off, really promising package, the various methods being attached to a connection keeps things very tidy.  I have been using `rmongodb` thus far, but this is a very welcome package.

I asked on [twitter](https://twitter.com/UTVilla/status/586205742245486592) about whether it is (or would be) possible for `mongo$find()` to return a list.  This might be something idiosyncratic (bad?) that I am doing, or an unnecessary complication on my part, but a number of my databases contain nested objects.  One such database contains a collection of horse races, each object contains data about the race conditions, as well as data about the runners, something like:

```json
{
    "_id": ["01/04/15_7"],
    "date": ["01/04/15"],
    "race": [7],
    "details": {
        "race_type": ["all op clm"],
        "dist": [5],
        "surf": ["turf"],
        "value": [50000]
    },
    "conditions": {
        "race_cond": ["nw2 x"],
        "clm_price": [62500],
        "f_m": [false],
        "runup": [165],
        "going": ["firm"]
    },
    "runners": {
        "trainer": ["christophe clement", "kelly j breen", "enebish ganbat", "charles dickey", "joseph calascibetta", "benjamin perkins jr", "peter d pugh", "benjamin perkins jr"],
        "jockey": ["edgard j zayas", "rafael manuel hernandez", "angel serpa", "edgar s prado", "eddie castro", "angel castillo", "mario g pino", "gabriel saez"],
        "j_clm": [0, 0, 0, 0, 0, 0, 0, 0],
        "age": [4, 5, 4, 5, 5, 5, 4, 4],
        "wgt": [121, 121, 121, 123, 121, 121, 121, 121],
        "gate": [8, 1, 3, 7, 5, 2, 6, 4],
        "pos": [1, 2, 3, 4, 5, 6, 7, 8],
        "horse": ["summation time", "bye bye bernie", "wild mongolia", "shadow rock", "noble prince", "tango on", "escapist", "hot heir skier"],
        "fintime": [54.79, 54.97, 55.05, 55.12, 55.17, 55.71, 55.95, 56.42]
    }
}
```

When `mongo$find(query = '{"_id": "01/04/15_7"}')` is called on the above entry, it returns a dataframe with just 6 variables, `_id`, `date`, `race`, `details`, `conditions` and `runners`.  The `details`, `conditions` and `runners` variables are dataframes, structure below.  

```r
'data.frame':	1 obs. of  6 variables:
 $ _id       : chr "01/04/15_7"
 $ date      : chr "01/04/15"
 $ race      : int 7
 $ details   :'data.frame':	1 obs. of  4 variables:
  ..$ race_type: chr "all op clm"
  ..$ dist     : int 5
  ..$ surf     : chr "turf"
  ..$ value    : int 50000
 $ conditions:'data.frame':	1 obs. of  5 variables:
  ..$ race_cond: chr "nw2 x"
  ..$ clm_price: num 62500
  ..$ f_m      : logi FALSE
  ..$ runup    : int 165
  ..$ going    : chr "firm"
 $ runners   :'data.frame':	1 obs. of  9 variables:
  ..$ trainer:List of 1
  .. ..$ : chr  "christophe clement" "kelly j breen" "enebish ganbat" "charles dickey" ...
  ..$ jockey :List of 1
  .. ..$ : chr  "edgard j zayas" "rafael manuel hernandez" "angel serpa" "edgar s prado" ...
  ..$ j_clm  :List of 1
  .. ..$ : int  0 0 0 0 0 0 0 0
  ..$ age    :List of 1
  .. ..$ : int  4 5 4 5 5 5 4 4
  ..$ wgt    :List of 1
  .. ..$ : int  121 121 121 123 121 121 121 121
  ..$ gate   :List of 1
  .. ..$ : int  8 1 3 7 5 2 6 4
  ..$ pos    :List of 1
  .. ..$ : int  1 2 3 4 5 6 7 8
  ..$ horse  :List of 1
  .. ..$ : chr  "summation time" "bye bye bernie" "wild mongolia" "shadow rock" ...
  ..$ fintime:List of 1
  .. ..$ : num  54.8 55 55 55.1 55.2 ...
```

Working with a dataframe like that would be possible, but ideally it would be a dataframe with 8 rows (one per runner), which are unique entries for a single race, and variables such as `date`, `race`, and `race_type` (found in details object), repeated for each of the entries.  I realise this is probably hard (impossible) for a package to cater for the huge number of possible structures that a BSON/JSON object could have.  If `mongo$find()` had an option to return a list (and a list of lists when returning multiple objects from a collection), so that `details`, `conditions` and `runners` seen above structure was preserved, then it would be easy for users of mongolite to write their own functions to _unpack_ their data.  The above JSON, using `jsonlite::fromJSON`, returns a nested list like:

```r
$`_id`
[1] "01/04/15_7"

$date
[1] "01/04/15"

$race
[1] 7

$details
$details$race_type
[1] "all op clm"

$details$dist
[1] 5

$details$surf
[1] "turf"

$details$value
[1] 50000


$conditions
$conditions$race_cond
[1] "nw2 x"

$conditions$clm_price
[1] 62500

$conditions$f_m
[1] FALSE

$conditions$runup
[1] 165

$conditions$going
[1] "firm"


$runners
$runners$trainer
[1] "christophe clement"  "kelly j breen"       "enebish ganbat"      "charles dickey"      "joseph calascibetta" "benjamin perkins jr" "peter d pugh"       
[8] "benjamin perkins jr"

$runners$jockey
[1] "edgard j zayas"          "rafael manuel hernandez" "angel serpa"             "edgar s prado"           "eddie castro"            "angel castillo"         
[7] "mario g pino"            "gabriel saez"           

$runners$j_clm
[1] 0 0 0 0 0 0 0 0

$runners$age
[1] 4 5 4 5 5 5 4 4

$runners$wgt
[1] 121 121 121 123 121 121 121 121

$runners$gate
[1] 8 1 3 7 5 2 6 4

$runners$pos
[1] 1 2 3 4 5 6 7 8

$runners$horse
[1] "summation time" "bye bye bernie" "wild mongolia"  "shadow rock"    "noble prince"   "tango on"       "escapist"       "hot heir skier"

$runners$fintime
[1] 54.79 54.97 55.05 55.12 55.17 55.71 55.95 56.42
```

From the list it's easy to convert into a desired dataframe.

```r
data.frame(id = race$`_id`, 
    date = race$date, 
    race = race$race, 
    data.frame(race$details), 
    data.frame(race$conditions), 
    data.frame(race$runners))

        id     date race  race_type dist surf value race_cond clm_price   f_m runup going             trainer
01/04/15_7 01/04/15    7 all op clm    5 turf 50000     nw2 x     62500 FALSE   165  firm  christophe clement
01/04/15_7 01/04/15    7 all op clm    5 turf 50000     nw2 x     62500 FALSE   165  firm       kelly j breen
01/04/15_7 01/04/15    7 all op clm    5 turf 50000     nw2 x     62500 FALSE   165  firm      enebish ganbat
01/04/15_7 01/04/15    7 all op clm    5 turf 50000     nw2 x     62500 FALSE   165  firm      charles dickey
01/04/15_7 01/04/15    7 all op clm    5 turf 50000     nw2 x     62500 FALSE   165  firm joseph calascibetta
01/04/15_7 01/04/15    7 all op clm    5 turf 50000     nw2 x     62500 FALSE   165  firm benjamin perkins jr
01/04/15_7 01/04/15    7 all op clm    5 turf 50000     nw2 x     62500 FALSE   165  firm        peter d pugh
01/04/15_7 01/04/15    7 all op clm    5 turf 50000     nw2 x     62500 FALSE   165  firm benjamin perkins jr
                 jockey j_clm age wgt gate pos          horse fintime
         edgard j zayas     0   4 121    8   1 summation time   54.79
rafael manuel hernandez     0   5 121    1   2 bye bye bernie   54.97
            angel serpa     0   4 121    3   3  wild mongolia   55.05
          edgar s prado     0   5 123    7   4    shadow rock   55.12
           eddie castro     0   5 121    5   5   noble prince   55.17
         angel castillo     0   5 121    2   6       tango on   55.71
           mario g pino     0   4 121    6   7       escapist   55.95
           gabriel saez     0   4 121    4   8 hot heir skier   56.42
```

Hope I've explained it well. Thanks

**Comment by jeroenooms** [comment]
Thanks this is a good example. I'll think about what is the best way to handle this.

**Comment by jeroenooms** [comment]
I see this is tricky with your nested one-to-many structure. But you can definitely get your data from the simplified output. For example: 

```r
# which record you want
i <- 1

# to get a single column
trainer <- race$runners[[i, "trainer"]]
id <- race[[i, "_id"]]
date <- race[[i, "date"]]

# get a nested list
runners <- as.data.frame(lapply(out$runners, `[[`, i))
conditions <- as.data.frame(lapply(out$conditions, `[[`, i))
details <- as.data.frame(lapply(out$details, `[[`, i))
```

So that gives a temporary solution, at least.

**Comment by durtal** [comment]
I get a small warning applying the above code, 
```r
Warning message:
In data.frame(..., check.names = FALSE) :
  row names were found from a short variable and have been discarded
```

but it does return the desired _fatter_ dataframe, so certainly a workaround.  I haven't tried inserting a list like that above, or updating one, but looking forward to trying :+1:

**Comment by jeroenooms** [comment]
The latest version includes a new method `m$iterate` which allows you to extract records one-by-one without simplification (and put them in a list if you like).

**Comment by durtal** [comment]
Excellent, will try it out later. 
Thanks for the great package.

**Comment by Spider08** [comment]
Thanks for the nice package @jeroenooms and the new functionality on the `m$iterate`. How to use the iterate function. Do you call it this way.?

    m$insert(cars)
    
    #to get the 10 rows
    for (i in 1:10) { 
    	row1 <- m$iterate()
    	#process row1
    }

Thanks again

**Comment by jeroenooms** [comment]
you need to first construct the iterator and then call it repeatedly. 

    m$insert(cars)
    iter <- m$iterate()
    while(!is.null(row <- iter())){
     #process row
    }

**Comment by Spider08** [comment]
Great. Thanks for the awesome package

**Comment by jeroenooms** [comment]
I have changed the iterator interface in the latest dev version :-) The `m$iterate()` function now returns an objects with several methods that you can use to read a single record, set of records, or a page. For example

```r
iter <- m$iterate()
while(!is.null(row <- iter$one())){
  # use row
}
```

But you can also get a batch (list) of records at once:

```r
iter <- m$iterate()
while(!is.null(set <- iter$batch(100))){
  # use set
}
```

**Comment by jeroenooms** [comment]
Support for iterators is on CRAN now. See this announcement: https://www.opencpu.org/posts/mongolite-release-0-5/

**Comment by jeroen** [comment]
@mnikolop I don't understand what you mean. Can you give me an example of this? I.e. an R script that inserts some data into a test db and then usres `iter()` to show me what it does funny?

**Comment by mnikolop** [comment]
@jeroen I will try to explain how the data is structured and give you an example of the query.
I have collection **col** and it has (among others) the fields **_id**, **uid**, **data** and the data field will contain a pair of a **timestamp** and a **value**. 
So when I run find on that data I get 95 entries that might have 1 or more data, that is put in a list, as expected. So I tried running iterate() to separate those **data** pairs in different lines (I might have read this thread completely wrong) like so:
```
i <- col$iterate(query = '{ "uid" : {"$oid": "x"} }', fields = '{"_id": true, "data.timestamp": true, "data.value": true}')
df <- data.frame()
while(length(x <- i$one())){
  #print(x)
  df <- smartbind(df, x)
}
```
This returns me a df of 96 lines with the first **data** point from the first line, and the first **data** point from all the rest. This is the "funny" part, because for example the **data** in the first line has 11 pairs of **timestamp** and **value** and line 2 has 10 and so on. 
And if I switch to using batch(n) it reads `i` every n lines and returns the first pair in the **data**.
Is that more clear?
I apologize for not being able to give a better example of the how the data actually looks.

**Comment by jeroen** [comment]
I suspect there is a bug in your `smartbind` function, whatever that tries to do. 

Below is an example of how you efficiently store the individual items into an environment. Perhaps you can adapt that to your needs.

```r
# Example data
col <- mongolite::mongo('mtcars')
col$insert(mtcars)

# Iterate
iter <- col$iterate(fields = '{}')
results <- new.env()
while(length(x <- iter$one())){
  id <- x[["_id"]]
  results[[id]] <- x
}
data <- as.list(results)
names(data) <- NULL
```

**Comment by mnikolop** [comment]
@jeroen thank you very much! Will try it! 
And thank you for this amazing package! :)
