### ISSUE TITLE
Connecting mongolite to SSL enabled Replica set

### ISSUE THREAD

**Issue by pvtpogopuschel** [jeroenooms/mongolite#30]
I'm having trouble connect to a SSL enabled replica set running on Ubuntu 14.04, MongoDB v3.0.5 via mongolite:

```
Error: No suitable servers found (`serverselectiontryonce` set): 
[connection timeout calling ismaster on 'xxprimaryxx.productioncluster.tld:27017'] 
[connection timeout calling ismaster on 'xxsecondaryxx.productioncluster.tld:27017']
Execution halted
```

Running `db.runCommand({"isMaster": 1})` on our primary node yielded the expected result:
```
{
	"setName" : "productionReplicaSet",
	"setVersion" : 1,
	"ismaster" : true,
	"secondary" : false,
	"hosts" : [
		"xxprimaryxx.productioncluster.tld:27017",
		"xxsecondaryxx.productioncluster.tld:27017"
	],
	"arbiters" : [
		"xxarbiterxx.productioncluster.tld:27017"
	],
	"primary" : "xxprimaryxx.productioncluster.tld:27017",
	"me" : "xxprimaryxx.productioncluster.tld:27017",
	"electionId" : 1,
	"localTime" : ISO1,
	"maxWireVersion" : 3,
	"minWireVersion" : 0,
	"ok" : 1
}
```

We use the following connection string, which is working fine for our nodejs based app:

```
mongodb://username:password@xxprimaryxx.productioncluster.tld:27017,xxsecondaryxx.productioncluster.tld:27017/database?replicaSet=productionReplicaSet&ssl=true
```

**Comment by jeroenooms** [comment]
@ajdavis is this connection string valid for the c driver?

**Comment by pvtpogopuschel** [comment]
According to http://api.mongodb.org/c/current/advanced-connections.html#replica-set - it is

**Comment by jeroenooms** [comment]
Could you try to specify the `db` argument in `mongo()` ?

**Comment by ajdavis** [comment]
The default database specification is not the issue. The driver is correctly trying to reach the two members, as you can see from the log messages. It can't connect, though. Watch the server logs, they'll tell you if the server is refusing the client connection due to the client's cert being invalid. If that's not the problem, then the most likely problem is the client can't validate the server's cert. If setting weak_validation on the client side allows the connection to succeed, then that's the problem and you need to fix the server cert. If the server cert is self-signed, provide the client with a CA file or directory:

http://api.mongodb.org/c/current/mongoc_ssl_opt_t.html

**Comment by pvtpogopuschel** [comment]
@ajdavis Thanks for your hint. I'll get back as soon as I've checked it.

**Comment by jeroenooms** [comment]
@pvtpogopuschel can you please close this issue if this turns out to be a server configuration problem?

**Comment by pvtpogopuschel** [comment]
@jeroenooms Sure, I'll keep you posted.

**Comment by ixgaming** [comment]
Do you have solved this problem ? I am having issues too to connect to a replicaset with ssl.

Thanks for your help

**Comment by DavidSichau** [comment]
I have the same Problem when I want to connect to mongodb atlas replica set.

**Comment by ajdavis** [comment]
That's helpful @DavidSichau ! So, @jeroenooms , I glanced through the repository and I don't see where mongolite uses mongoc_ssl_opts_t to configure the client certificate and other options. Does it? If not, you'll need to provide mongolite users some way to set the options in this struct:

http://mongoc.org/libmongoc/current/mongoc_ssl_opt_t.html

Hannes has written a nice guide on that page to what's supported and what the options mean. See also:

http://mongoc.org/libmongoc/current/advanced-connections.html#SSL

**Comment by jeroenooms** [comment]
@ajdavis thank you, I will try to find some time to work on this. 

By the way, it would be more convenient if the user could set such settings via environment variables and `libmongoc` would automatically pick up on it. That way users can specify system wide ssl options that work for all drivers rather than adding bindings for everything.

**Comment by DavidSichau** [comment]
@jeroenooms I can give you the access to our test replica set, if this reduces you work. The you can test it without setting it up.

**Comment by EnricowithR** [comment]
how can I connect in R to a mongodb with a SSL connection by using mongolite?

**Comment by ajdavis** [comment]
@EnricowithR what we've figured out is, if you pass a MongoDB URI to mongolite like:
```
mongodb://mydatabase.com/?ssl=true
```
... then the client connects to the server via SSL, and it presents no client certificate. That'll work, *if* that server is configured with [allowConnectionsWithoutCertificates](https://docs.mongodb.com/manual/reference/configuration-options/#net.ssl.allowConnectionsWithoutCertificates).

More often, the server is configured to require client certificates. (This is the default.) mongolite does not yet support sending a client cert to the server, so you cannot connect to MongoDB in this scenario.

**Comment by EnricowithR** [comment]
or do you know if it possible to do that with the package Rmongo?

**Comment by jeroenooms** [comment]
@DavidSichau if you can give me access to a test server, that would be great.

**Comment by DavidSichau** [comment]
It works with the current development version:

    devtools::install_github("jeroenooms/mongolite")

**Comment by jeroenooms** [comment]
I have imported `mongo-c-driver 1.4.1` into `mongolite` which seems to solve part of the problem. However I still don't have access to a mongodb server that allows me to test SSL options (setting a PEM file and so on).

**Comment by ajdavis** [comment]
@jeroenooms the freely downloadable MongoDB has SSL built in:

https://www.mongodb.com/download-center#community

With MongoDB 3.2, you can start it from the C Driver's root directory with the SSL files included in our repository for testing:
```
mongod \
   --sslMode requireSSL \
   --sslPEMKeyFile tests/x509gen/server.pem\
   --sslCAFile tests/x509gen/ca.pem
```
Now it's listening for SSL. You can check that the client side is properly configured by running the C Driver test suite:
```
export MONGOC_TEST_SSL_PEM_FILE=tests/x509gen/client.pem 
export MONGOC_TEST_SSL_CA_FILE=tests/x509gen/ca.pem
make test
```
If that works you're ready to test mongolite. For reference, [here's how the C Driver suite sets SSL options from environment variables](https://github.com/mongodb/mongo-c-driver/blob/69ab5ff18a770568e15af0f6bbacbcd58f8891ac/tests/test-libmongoc.c#L1378-L1378).

**Comment by jeroenooms** [comment]
@ajdavis @bjori Am I correct to assume that `client.pem` always contain both a `CERTIFICATE` and a `PRIVATE KEY` entry? Or is there also a case where the client only has a certificate but no private key?

**Comment by bjori** [comment]
@jeroenooms Yes, you need both in the same file. Currently we don't support providing these in separate files, and have no plans for doing so.

**Comment by jeroenooms** [comment]
OK so the logic is not entirely clear to me. When I compare this to HTTPS, only the server has a private key. The client simply verifies the server cert + signature against his local CA.

But I guess you are using SSL both for client authentication of the client and the server?

**Comment by jeroenooms** [comment]
Also I don't think the private key should be in `ca.pem` ??

**Comment by bjori** [comment]
In HTTPS the client verifies the server. The server does not verify the client, and does not request a client certificate.

The SSL protocol however isn't only about encryption, it also allows for authentication and identity verification. In the case of https, it makes no sense for the server to authenticate the client. You want all clients being able to view the website. For most other protocols it however is required part. You don't want anyone even talking to the server without being allowed to do so.

In the case of MongoDB, we request the client certificates. It is configurable on the `mongod` if it should accept connections from clients that do not provide client certificates (`--sslAllowConnectionsWithoutCertificates`), in which case you don't have to provide `client.pem` at all.

Note that these certificates are not to be confused with authentication. These are only for authorization

**Comment by bjori** [comment]
No, the private key does not need to be in `ca.pem`.
I am aware that our test suite does include it in our `ca.pem` file. There is no reason for that other then I didn't want to loose it.

It does no harm.

**Comment by jeroenooms** [comment]
OK I implemented everything. I ended up parsing the keys/certs in R, validating them, and then writing them to a temporary `client.pem` file which I give to `mongo-c-driver`. This way R users can specify their certs and keys in separate files.

Also if there is an error with the cert/key they get caught immediately, and if they key is password protected the user gets a nice secure password dialog. 

If any one can test this, that would be great:

```r
devtools::install_github("jeroenooms/mongolite")
```

You want to set the `options` argument in `?mongo`. See `?ssl_options` for the parameters.

**Comment by ixgaming** [comment]
Great ! working very well with my mongo db atlas cloud : 
mongodb 3.2.9 with replicaset and ssl enabled !

**Comment by jeroenooms** [comment]
@bjori @ajdavis I was trying to figure out why this only worked locally but I could not connect from other machines in my LAN. The problem was that your `tests/x509gen/ca.pem` file only is valid for "localhost" connections. So you can use it to test via `mongodb://localhost/` but not `mongodb://192.168.1.10` even if that is your local ip address.

Perhaps you should relax the `alt_names` on that test cert. Other than that it seems to work.

**Comment by bjori** [comment]
The `ca.pem` is the certificate authority that signed `server.pem` and `client.pem`.
I suspect you meant to say `server.pem` is only valid for `localhost` (and `127.0.0.1`). That is correct.

You cannot create a certificate which matches an IP range as far as I know, and wildcards are not allowed in IP addresses.

We do have `altname.pem` and `wild.pem`. The former matches `localhost` and `alternative.mongodb.com` while the latter matches `*.mongodb.org`.

If you add `192.168.1.10 example.mongodb.org` to your `/etc/hosts` and startup `mongod` with `--sslPEMKeyFile wild.pem` and connect to `mongodb://example.mongodb.org` then it should work.


--

Note that the CA that signed these certificates is not production CA so attempting to use these certificates to pretend to be mongodb.com on the internet will not have any affect. It will however work fine if you temporarily edit your `/etc/hosts` :)

**Comment by jeroenooms** [comment]
A new version of mongolite with `ssl_options` is on CRAN now.
