### ISSUE TITLE
Use message instead of Rprintf

### ISSUE THREAD

**Issue by hrbrmstr** [jeroenooms/mongolite#31]
via http://stackoverflow.com/questions/36152511/how-can-you-turn-off-messages-in-mongolite-r-package

this bit of code: https://github.com/jeroenooms/mongolite/blob/2bca2663e7e743e4f9591abe99228bf6a2ef6c27/src/onload.c#L15

uses `Rprintf` instead of the R message system, forcing users to resort to things like `capture.output` vs `suppressMessage`

3 places:

    onload.c:15:    Rprintf("Mongo Message: %s\n", message);
    reader.c:58:      Rprintf("\rRestored %d records...", count);
    reader.c:62:    Rprintf("\rDone! Inserted total of %d records.\n", count);

**Comment by jeroenooms** [comment]
Is there a C api for messages?

**Comment by hrbrmstr** [comment]
no, sadly just `warning` and `error` from what I've been able to tell. in `Rcpp` (my lazy way to use C in packages vs your elegant way ;-) I'd do something like:

    Rcpp::Function R_message("message");

then just be able to call `message("the message")`

I was going to poke at what wld need to be done to do the same thing from the C interface.

**Comment by hrbrmstr** [comment]
It would see <http://pabercrombie.com/wordpress/2014/05/how-to-call-an-r-function-from-c/> is a viable solution to getting to R's `message()`

**Comment by eddelbuettel** [comment]
Yes, because @jeroenooms insists on not using Rcpp for C packages he gets to reinvent it, slowly.

(WIth apologies to Henry Spencer](https://en.wikipedia.org/wiki/Henry_Spencer) for the best tech aphorysm, ever.)

**Comment by hrbrmstr** [comment]
This seems to do it
```
void R_message(const char *txt) {
  SEXP r_msg = install("message");
  SEXP call_msg = PROTECT(lang2(r_msg, ScalarString(mkChar(txt))));
  eval(call_msg, R_BaseEnv);
  UNPROTECT(1);
}
```

**Comment by jeroenooms** [comment]
@hrbrmstr thanks that's helpful but a bit ugly, indeed. I think I'll take another approach where we actually let the user set the log level. @eddelbuettel not too helpful.

**Comment by eddelbuettel** [comment]
@jeroenooms In all seriousness I do use Rcpp for those use cases too.  Why waste time reinventing plumbing and build tools when you could focus on Mongo bindings?

But hey, we all have our own priorities and you're a big boy ...

**Comment by jeroenooms** [comment]
We talked about this. Go rewrite digest in Rcpp or something

**Comment by eddelbuettel** [comment]
I have a few plain C packages: digest, RApiSerialize, ...  But they are all minimal and don't need anything fancy.  When I do I pick that for free from Rcpp.   But sure, reinvent away.

**Comment by eddelbuettel** [comment]
And I did look at `message()` briefly and it doesn't look as if we could cheaply do `RApiMessage` -- seems to all be at the R level.  Yet if we exported a header with a clean C callable interface, we'd all be better off.

Until then `Rcpp::Function msg("message")` for me.

**Comment by jeroenooms** [comment]
Fixed @ https://github.com/jeroenooms/mongolite/commit/a83aa97fd88f7a3d02e59d1eb2be69cf338c9ad5. You can now set a custom log level via `mongo_log_level`.

**Comment by jeroenooms** [comment]
Hadley's [r-internals](https://github.com/hadley/r-internals/blob/master/error-eval.md) hints at the an API `R_ShowMessage` but I'm not sure if that's the same as a regular R message. 

```c
void  R_ShowMessage(const char *s);
```

**Comment by eddelbuettel** [comment]
Not working with `suppressMessages()`:

```r
R> library(Rcpp)
R> cppFunction("void msg(std::string txt) { R_ShowMessage(txt.c_str()); }")
R> msg("foo not bar")
foo not bar
R> suppressMessages(msg("foo not bar"))
foo not bar
R> 
```

**Comment by jeroenooms** [comment]
Hmmm yes and in some GUI's this results in a popup rather than a terminal message. I suppose it's something different then.
