### ISSUE TITLE
mongolite find returns _id as raw bytes in dataframe

### ISSUE THREAD

**Issue by theroys** [jeroenooms/mongolite#32]
I am using mongolite with data hosted in mongolab where objects have id like
"_id": {
        "$oid": "5596dc89e4b05ea68b35c2a1"
    }
db version 3.0.7
Using 
1.RStudio Version 0.99.491
2.R 3.2.3
using find with {"_id" : 1,...} returns a ids as dataframe containing raw bytes rather than character vector 
e.g.
test
                                             _id
1 55, 98, 6e, 1b, e4, b0, a6, 17, 55, 0b, 3f, 90
as.character(test[1,])
[1] "as.raw(c(0x55, 0x98, 0x6e, 0x1b, 0xe4, 0xb0, 0xa6, 0x17, 0x55, 0x0b, 0x3f, 0x90))"

Is this expected behavior
to get the id out as string, i can do some workarounds but all of them are convoluted
e.g.
a<-as.character(test[1,][[1]])
myid<-paste(a,collapse = "")
..i wonder why the api the id in such a way.. why not json object(not flattened)
Is this by design

**Comment by jeroenooms** [comment]
Yes this is expected. An object ID in mongo consists of bytes so they turn into raw vectors. But perhaps a string would make more sense, is what you are saying?

**Comment by theroys** [comment]
yes :) that would reduce the pain of converting it into a string and can be readily used.

**Comment by jeroenooms** [comment]
I have to think a little bit if this would have any unfortunate side effects though.

**Comment by theroys** [comment]
Would you like a pull request for this

**Comment by jeroenooms** [comment]
Sure you can suggest a change with a PR

**Comment by BetweenTwoTests** [comment]
Second this request. If I have to find the exact document but didnt specify an id (because I asusmed _id will be sufficient), It is more difficult to query that document.

**Comment by jeroenooms** [comment]
Fixed @ https://github.com/jeroenooms/mongolite/commit/4ae40123be32d5001e42e4d7a8d147f8347a4cad.
