### ISSUE TITLE
Upsert with mongolite?

### ISSUE THREAD

**Issue by iainmwallace** [jeroenooms/mongolite#33]
Is it possible to do a bulk upsert with mongolite? 

I am trying to insert a lot of data (millions of documents) into mongodb using R from a variety of data frames which I will obtain at different times.

Each data frame will have the same primary id, but can have the same or different attributes.

If the record exists, I would like to add any new attributes and append any existing ones. If the record doesn't exist, I would like to create it.

When I use the m$insert approach, I get an error as the record already exists. 

I have also posted this question to Stackoverflow
http://stackoverflow.com/questions/36208208/bulk-insert-update-using-r-to-mongodb

Thanks

Iain

id<-LETTERS[1:5]
value1<-paste0("value1_",letters[1:5])
value2<-paste0("value2_",letters[1:5])
value3<-paste0("additional_value_1",letters[1:5])
df1<-as.data.frame(cbind(id,value1))
df2<-as.data.frame(cbind(id,value2))
df3<-as.data.frame(cbind(id,value3))

colnames(df1)<-c('_id','value1')
colnames(df2)<-c('_id','value2')
colnames(df3)<-c('_id','value1')

desired_value1<-paste0(  [",paste(paste0("'",value1,"'"),paste0("'",value3,"'"),sep=","),"]")
df4<-cbind(id,desired_value1,value2)
df4<-as.data.frame(cbind(id,desired_value1,value2))
colnames(df4)<-c("_id","value1","value2")

**Comment by jeroenooms** [comment]
This should be possible now, see the new docs: https://jeroenooms.github.io/mongolite/manipulate-data.html#update-upsert. Please LMK if this is what you need.
