### ISSUE TITLE
Aggregation fails for large queries

### ISSUE THREAD

**Issue by DavidSichau** [jeroenooms/mongolite#36]
I have an aggregation that extends the internal memory limits. Via the mongo shell I need to provide the argument `{allowDiskUse: true}` to the aggregation function.

The problem is that mongolite fails silently and does not return anything. And I found no way to pass the options to the aggregate function such, that this query would be possible.

E.g. something like:

    mongo_logs$aggregate('[{ "$group": {
                    "_id": {
                        "user": "$userIdentifier",
                        "mdId": "$log.mdID"
                    }, 
                    "count": { "$sum" : 1 },
                    "time": {"$sum": "$log.time"},
                    "access": { "$push":  {
                        "day": {"$dayOfYear": "$createdAt"},
                        "year": {"$year": "$createdAt"},
                        "minutes": { "$minute": "$createdAt" }
                    }}
                }}]', '{"allowDiskUse": true}')

**Comment by pevzner** [comment]
I am seeing the same problem. Ability to specify {allowDiskUse: true} for aggregation would be very valuable.

**Comment by jeroenooms** [comment]
@ajdavis what is the equivalent of `allowDiskUse` in the C driver?

**Comment by ajdavis** [comment]
Just add "allowDiskUse": true to the "options" param to
mongoc_collection_aggregate. Follow the example at the bottom here:

https://api.mongodb.com/c/current/mongoc_collection_aggregate.html#options

... but substitute "allowDiskUse" for "bypassDocumentValidation".

General command info for "aggregate":

https://docs.mongodb.com/manual/reference/command/aggregate/

**Comment by morganmadell** [comment]
Any further work on this?  I have the same problem: I can add "allowDiskUse" to my shell commands but can't see how to do this using mongolite.

**Comment by pevzner** [comment]
The rmongodb library supports the allowDiskUse functionality, so I've been using that instead. But generally speaking I like mongolite better, so looking forward to this getting implemented.

**Comment by morganmadell** [comment]
With rmongodb I had trouble connecting to our new mongo server.  I switched to mongolite as it supports SCRAM authentication.  Getting this feature implemented would be great.

**Comment by jeroenooms** [comment]
I'll try to have a look at this soon. If you can send a PR that might speed things up :)

**Comment by jeroenooms** [comment]
Fixed @ https://github.com/jeroenooms/mongolite/commit/ad8f41d74031724d4ebadf1f238717e64af4b521. You can now pass an `options` object to aggregate.
