### ISSUE TITLE
Use double data type to all numeric values

### ISSUE THREAD

**Issue by fabioand2k** [jeroenooms/mongolite#38]
Hello,

please how can i force to save in collection from dataframe all numeric values as double ?

this is my json extracted from my dataframe
[
{"Type":"Hybrid","Origin":"Asia","Mode":55},
{"Type":"Sedan","Origin":"Asia","Mode":18},
{"Type":"SUV","Origin":"Europe","Mode":14.25}
]

the column Mode is storaged in mongo collection in  first two rows as int32 and third row storage as double.

my problem is when i try to retrieve this collection in c# program this column is converted as string, because has two datatypes. (using dataadapter to fill a datatable).

please help me.
thanks

**Comment by jeroenooms** [comment]
The `mode` column will always be double when there is a mix of whole numbers and reals. But you can force after retrieving the data like this:

```r
df$Mode <- as.numeric$df$Mode)
```

Saving this as string makes no sense, but you can use `as.character` if you want to do so.

**Comment by fabioand2k** [comment]
Hi jeroenooms,

thank you so much.

please run this code:

library(mongolite)
library(plyr)
library(dplyr)


employee <- c('John Doe','Peter Gynn','Jolie Hope')
salary <- c(21, 23.4, 26.00)
employ.data <- data.frame(employee, salary)

dbinserir <-  mongo(url = 'mongodb://localhost',collection = 'newcollection_mongolite', db = 'novobanco')
if(dbinserir$count() > 0) dbinserir$drop()
employ.data$salary <- as.numeric(employ.data$salary)
dbinserir$insert(employ.data,pagesize = 1000)

and see my picture. you'll see the different types os numeric value.

what i need is save all records with the same mongo datatype.

thanks!
![mongolite](https://cloud.githubusercontent.com/assets/14325999/15318391/3c06c23c-1bfc-11e6-81f1-89798b69141a.png)

**Comment by jeroenooms** [comment]
I don't think I can control that. The R driver inserts the data via json, and I guess mongodb defaults to storing whole numbers as integers...

**Comment by fabioand2k** [comment]
Hi,
i did this to resolve:
is.num <- sapply(databb, is.numeric)
databb[is.num] <- lapply(databb[is.num], '+' , .0000000001)

thanks!

**Comment by jeroenooms** [comment]
This should be fixed now in jsonlite https://github.com/jeroenooms/jsonlite/commit/1e75b59b87f9653f206c253aab5939d6e96cb1f3?w=1 and mongolite  https://github.com/jeroenooms/mongolite/commit/e439c597a07d13a0e0964b517dc4f84c66e509e1. Let me know if you have a chance to test this.

**Comment by fabioand2k** [comment]
Works like a charm!!!
thanks my friend!
sorry about delay answer.
