### ISSUE TITLE
Hi there

### ISSUE THREAD

**Issue by khushwinder** [jeroenooms/mongolite#39]
I am new to mongolite and R. i am finding it very good for interacting with my mongodb database. But i have googles a lot but could not find any tutorial or example which shows creating a plot or graph with the help of mongolite database.
If you are aware of any links please let me know. Thanks in advance.

**Comment by HanOostdijk** [comment]
Presentation and storage of data are more or less independent (orthogonal ?) .
A nice package for presenting data (some would say THE package) is ggplot2.
I found an example on the [web](http://tillbergmann.com/blog/mongodb-in-r.html) where both packages are used.

**Comment by khushwinder** [comment]
Thanks a lot for your reply Han. I agree they are different but  still if i am using R its mean i will be using it for presentation and there should be some kind of relationship between storage and presentation. My only concern is for a naive developer (i do have good experience in java) there should be more example. Otherwise thanks also for reference link.
