### ISSUE TITLE
How to insert nested lists?

### ISSUE THREAD

**Issue by vspinu** [jeroenooms/mongolite#42]
Hi. The package is truly great except that it assumes data.frames throughout. How can I store a nested named list?  Thanks.

**Comment by vspinu** [comment]
Related - #23. It was closed with no fix.

**Comment by jeroenooms** [comment]
The dev version of mongolite allows you to insert a single record with a named list or a set of records via a character vector of json objects. So you should be able to do:

```r
# insert single record
m <- mongo("test")
x <- list(foo = 123, bar = TRUE)
m$insert(x)
```
or
```r
# insert set of records as json objects
records <- c(
  '{"foo":123, "bar": true}',
  '{"foo":456, "bar": false}'
)
m$insert(records)
```

Obviously you don't have to hardcode the json, you should use `jsonlite::toJSON` to generate the character vector with json records from your data (duh).

**Comment by vspinu** [comment]
Perfect. It works. Thanks!
