### ISSUE TITLE
How to match date on Aggregation pipeline

### ISSUE THREAD

**Issue by K2GThe1** [jeroenooms/mongolite#44]
I have an aggregation, i want to match on date, this is my aggregation:

``` r
records<-quantDB$aggregate('[
  {"$match":{"purchaseDate":{$gte: ISODate("2016-07-01T00:00:00.0Z"), $lt: ISODate("2016-07-20T00:00:00.0Z") } } }
]')
```

Thanks.

**Comment by jeroenooms** [comment]
Try something like this:

```r
query <- list(
  list(
    "$match" = list(
      "purchaseDate" = list(
        "$gte" = as.POSIXct("2016-07-01T00:00:00.0Z"),
        "$lte" = as.POSIXct("2016-07-20T00:00:00.0Z")
      )
    )
  )
)

qstring <- toJSON(query, auto_unbox = TRUE, POSIXt = "mongo")
records<-quantDB$aggregate(qstring)
```

**Comment by K2GThe1** [comment]
Thanks Jeroenooms, i have no problem during execution but 0 records. please what can be the problem.
Thanks.

**Comment by jeroenooms** [comment]
The new documentation has examples on matching by datetime: https://jeroenooms.github.io/mongolite/query-data.html#select-by-date. Hope this solves your problem.

**Comment by SaswatMahapatra** [comment]
Hi @jeroen , 


I have this query , and the error im getting is invalid JSON data , can you please tell me where am I going wrong in this .

alldata <- newdb$aggregate('["$match": { "created": { "$gte" : ISODate("2018-07-01T00:00:00.000+0000")}},
                            {"$unwind": "$uid"},
                            {"$group": {"_id":{"$dateToString" : {"$date" : "$created", "format" : "%Y-%m-%d"}},
                             "$jobseekers":{"$addToSet" : "$uid"}}},
                            {"$project": {"$js" : {"$size" : "$jobseekers"}}},
                            {"$sort": {"_id":1}}]', options = '{"allowDiskUse":true}')


Error: Invalid JSON object: ["$match": { "created": { "$gte" : ISODate("2018-07-01T00:00:00.000+0000")}},
                            {"$unwind": "$uid"},
                            {"$group": {"_id":{"$dateToString" : {"$date"

**Comment by jeroen** [comment]
`ISODate()` is not json, you need to use `{"$date": ... } instead.

**Comment by SaswatMahapatra** [comment]
{"created": { "$gte" : {"$date":("2018-07-01T00:00:00.000+0000")}}


same error im getting

**Comment by SaswatMahapatra** [comment]
like this is my query : 

db.getCollection("dailyUserHistory").aggregate(

	
	[
		
		{
			$match: { "created": { $gte: ISODate("2018-07-01T00:00:00.000+0000"), $lt: ISODate("2018-08-01T00:00:00.000+0000") } }
		},

		
		{
			$unwind: "$uid"
		},

		
		{
			$group: {
			_id:{"$dateToString" : {"date" : "$created", "format" : "%Y-%m-%d"}},
			jobseekers:{"$addToSet" : "$uid"}
			}
		},

		
		{
			$project: {
			js : {"$size" : "$jobseekers"}
			}
		},

		
		{
			$sort: {
			_id:1
			}
		},
	],

	
	{
		allowDiskUse: true
	}

	);


i want to use this query to fetch data from collection... im unable to do so. 
can you help me here...

**Comment by SaswatMahapatra** [comment]
@jeroen  can you please help here

**Comment by SaswatMahapatra** [comment]
hi @jeroen  match condition when used with aggregation doesnt work. can you please check the issue. I tried every possible options.

alldata <- newdb$find('{"created": {"$gte": {"$date": "2018-07-01T00:00+0500" }}}')
This works fine.

And when I use the same thing with aggregate function , it doesnt work.
alldata <- newdb$aggregate('["$match":{"created": {"$gte": {"$date": "2018-07-01T00:00+500" }}},
                            {"$unwind": "$uid"},
                            {"$group": {"_id":{"$dateToString" : {"$date" : "$created", "format" : "%Y-%m-%d"}},
                             "jobseekers":{"$addToSet" : "$uid"}}},
                            {"$project": {"$js" : {"$size" : "$jobseekers"}}},
                            {"$sort": {"_id":1}}]', options = '{"allowDiskUse":true}')


Somehow I feel this is bug. Can you fix it ?
