### ISSUE TITLE
Query help for date stored as string

### ISSUE THREAD

**Issue by SantoshSrinivas79** [jeroenooms/mongolite#46]
This code works in the MongoDB shell .. 

``` js
db.eq_bhav.find({   "TIMESTAMP" : {      $gte: Math.floor(Date.parse("2015-01-01")/8.64e7)   }    })
```

How do I port this to mongolite? I tried the following

qry <- 'db.eq_bhav.find({"TIMESTAMP" : {"$gte": Math.floor(Date.parse("2015-01-01")/8.64e7)}})'
con$find(qry)

I get `Error: Invalid JSON object`

I tried adding the quotes but it still doesnt work.

Note: My dates are stored as "days" e.g. as.integer(Sys.Date())

**Comment by jeroenooms** [comment]
Can you try this?
```r
query <- list(TIMESTAMP = list("$gte" =  as.POSIXct("2015-01-01")))
str <- jsonlite::toJSON(query, auto_unbox=TRUE, POSIXt = "mongo")
db.eq_bhav.find(str)
```

**Comment by SantoshSrinivas79** [comment]
@jeroenooms I solved this using:

```r
start_date <- as.integer(as.Date("2015-01-01"))
query <- paste('{"TIMESTAMP" : {"$gte": ',start_date,' }}', sep='')
d <- con$find(query)
```

But, I'm wondering if there is no way to put nodejs stuff `Math.floor(Date.parse` etc ... because what I was thinking is if shell is able to execute it .. there should a way to pass exactly same query strings from R and have them executed within MongoDB.
I may not understand the internals but just wanted to check.

**Comment by jeroenooms** [comment]
Please see the section on [selecting by date](https://jeroenooms.github.io/mongolite/query-data.html#select-by-date) in the new documentation. Note that a **date** in R is not the same as a Mongo **datetime**...

**Comment by nimame** [comment]
@jeroen: for clarification, can you confirm that this is working:

```R
query <- list(TIMESTAMP = list("$gte" =  as.POSIXct("2015-01-01")))
str <- jsonlite::toJSON(query, auto_unbox=TRUE, POSIXt = "mongo")
```

Because str gives: `{"TIMESTAMP":{"$gte":[{"$date":1420070400000}]}} `
...and I'm think the brackets around the "$date" object are not allowed? Is there a way to remove them using jsonlite::toJSON? I'm trying to avoid concatenating strings and variables to build my queries, but stumbled over this issue.

**Comment by jeroen** [comment]
@nimame can you open a new issue for this? This might be a bug (but I don't have time to look into it immediately)
