### ISSUE TITLE
Need an argument to suppress authentication messages

### ISSUE THREAD

**Issue by renkun-ken** [jeroenooms/mongolite#49]
Currently, if the mongo connection is established with authentication, there will by always 3-step authentication messages like

```
Mongo Message: SCRAM: authenticating "root" (step 1)
Mongo Message: SCRAM: authenticating "root" (step 2)
Mongo Message: SCRAM: authenticating "root" (step 3)
Mongo Message: SCRAM: "root" authenticated
```

Although I can use `capture.output` or `sink` to suppress such printing, It would be nice to have an argument to do so because `capture.output` and `sink` can be overkill when the arguments passed to `mongo` produce errors.

**Comment by jeroenooms** [comment]
Try `mongolite::mongo_log_level(3)`

**Comment by renkun-ken** [comment]
Thanks! Just noticed that `mongolite::mongo_log_level` is not yet available in CRAN version. I'll try with the latest dev.

**Comment by MaggieSaavedra** [comment]
Hi thank you for this but I am just wondering if there is also a way to suppress messages every after query

I got this message:  Imported 67 records. Simplifying into dataframe...
I tried using mongolite::mongo_log_level but nothign works. 
Hope you can help me with this

Thank you!

**Comment by jeroenooms** [comment]
Did you try connecting with `mongo(.... , verbose = FALSE)` ?
