### ISSUE TITLE
Users, use-cases, testers, feedback, suggestions

### ISSUE THREAD

**Issue by jeroenooms** [jeroenooms/mongolite#5]
Mongolite is now at MVP stage with basic functionality for reading and writing to/from MongoDB in R implemented. I would be interested to hear from users that (want to) use mongo with R if this fits your needs and what additional low- or high-level functionality might be useful to add to the package.

Documentation is sparse but the [readme](https://github.com/jeroenooms/mongolite#readme) should be a good start. Make sure you use the latest version of the package:

```r
devtools::install_github("jeroenooms/mongolite")
```

Comments and ideas welcome below.

**Comment by cronacronis** [comment]
It would be great to store `type_meta_data`, somewhere in the document for every field, for types inference. Thus, when `data.frame` is prepared in R, columns will be casted to corresponding type. For most of the types there is bijective correspondence in R and mongodb. Thus, on insert and get there is no even a need for a `type_meta_data`. Also follow standards of conversion of `NA` and `NULL` for every type.

**Comment by mattjmorris** [comment]
I love how quickly this package converts my data to a data.frame. Thanks so much for publishing this. One thing I'm having difficulty doing is searching a collection based on dates. I was able to do this with rmongodb but want to convert everything over to mongolite. Is it possible to do something like "$gte": strptime("2015-09-10","%Y-%m-%d") in a find() in mongolite?

**Comment by jeroenooms** [comment]
Good question. Maybe @ajdavis know the correct syntax for a date range query with [mongo-c-driver](https://github.com/mongodb/mongo-c-driver)?

**Comment by mattjmorris** [comment]
I was able to get date-based queries working with the code show below. Thanks again for doing this package - it is making my code base much cleaner.

datemillis <- as.integer(as.POSIXct(strptime("2015-11-20","%Y-%m-%d"))) * 1000
data <- data_collection$find(qq('{"createdAt":{"$gt": { "$date" : { "$numberLong" : "@{datemillis}" } } } }'))

**Comment by ajdavis** [comment]
Glad you got it working!

**Comment by tospig** [comment]
@mattjmorris this may be off-topic, but do you need the `strptime()` call, can you not just use 

    as.integer(as.POSIXct("2015-11-20")) * 1000

Either way, I've was pointed to your great solution through [this stackoverflow](http://stackoverflow.com/q/34454034/4002530) question. And I've also created the `mongolite` tag.

**Comment by SymbolixAU** [comment]
To avoid [this issue of incorrect number of digits](http://stackoverflow.com/a/36563386/5977215) it might be worth setting `options(scipen=1000)` prior to date queries.

**Comment by HanOostdijk** [comment]
I like this package very much. My current use-case is selecting from a large file and writing the intermediary results to a collection. Sometimes the result contains many fields and sometimes only a few. When I do a find for the whole collection it will return all those fields but for queries I notice that only the fields with contents are returned and I like that!
One remark: I noticed that the **remove** method has a parameter *multiple* while the [mongodb documentation](https://docs.mongodb.org/manual/reference/method/db.collection.remove/) has *justOne*.That was a little confusing because in case of doubt I use the mongodb docs.
