### ISSUE TITLE
Cannot configure trusted SSL CA file 

### ISSUE THREAD

**Issue by hideaki** [jeroenooms/mongolite#50]
I set up a mongod server with SSL with self-signed certificate.
I can connect to it with mongo shell client by specifying the certificate by --sslCAFile option.
```
sw/mongodb-osx-x86_64-3.2.6/bin/mongo --host localhost --ssl --sslCAFile /Users/hideaki/etc/ssl/mongodb-cert.crt
```
However, I cannot find a way to specify trusted SSL cert for mongolite.
Connecting to the server with url of "mongodb://localhost?ssl=true" results in failure.
Looking into the SSL handshake with wireshark, the client (mongolite) seems to be rejecting server based on "Unknown CA".
So, I believe this should be solved if I can set up trusted CA cert on mongolite, but I can't find a way to do that. Is there any way to do that, or could you add some means to configure it?

**Comment by jeroenooms** [comment]
Please continue discussion at https://github.com/jeroenooms/mongolite/issues/30. If you can give me an example server to test this, that would be amazing.
