### ISSUE TITLE
Are there any restrictions on the "query" parameter of the iterate method ?

### ISSUE THREAD

**Issue by diegocaseonit** [jeroenooms/mongolite#51]
I tried to use $match, $group and $project as stages on my query parameter when using the iterate method, but I get an error message that states the JSON object is invalid. I run the same query using the aggregate method with no problem. 

Therefore I'm wondering what are the restrictions on the query parameter of the iterate method? Are they also restrictions on the fields parameter?

**Comment by jeroenooms** [comment]
No, they should be exactly identical. Can you please post your query string if this is still a problem in the latest version?

**Comment by diegocaseonit** [comment]
Thanks, I solved the problem. I figure out that I was using quotes around integers, but I did not need them;  my incorrect stage of the query was
stage1 = paste('"$match": { "name":"diego" ,"age": "3" ,"place": "',location[i],'" }' ,sep='')

and the CORRECT stage was
stage1 = paste('"$match": { "name":"diego" ,"age": 3 ,"place": "',location[i],'" }' ,sep='')
