### ISSUE TITLE
mongo 3.2 Replicaset and SSL

### ISSUE THREAD

**Issue by ixgaming** [jeroenooms/mongolite#53]
How to use it with mongo 3.2.9 with replicaset and SSL authentication ?

do you plan to update the driver ?

**Comment by DavidSichau** [comment]
see #30 for details on this problem.

**Comment by jeroenooms** [comment]
I think this should be solved now, but please continue the discussion in https://github.com/jeroenooms/mongolite/issues/30. Thank you!
