### ISSUE TITLE
array name

### ISSUE THREAD

**Issue by snagahuiyan74** [jeroenooms/mongolite#55]
I'm trying to use array name in $find of the codes below, it says invalid JSON object. Why is that? Thanks very much.

Snagger

library(mongolite)
library(jsonlite)
id <- c('35325073','35325078')
id_list_JSON <- toJSON(id)
test3 <- m1$find('{"_id": {"$in": "id_list_JSON"}}', fields = '{"_id" : 1, "f.fid" : 1, "ud" : 1}')
Error: Invalid JSON object: {"_id": {"$in": "id_list_JSON"}}

**Comment by jeroenooms** [comment]
You need to form an actual JSON string, you can't reference the R variable name `id_list_JSON` in your JSON.
