### ISSUE TITLE
Connection issue

### ISSUE THREAD

**Issue by antaldaniel** [jeroenooms/mongolite#56]
There is a known connection issue with mongodb documented [here](https://github.com/mongodb/mongo-php-driver/issues/133) and [here](https://jira.mongodb.org/browse/PHPLIB-151).  I ran into it on a Windows10 system, but apparently this happens with several OS's. The problem is connected to the fact that the mongodb driver does not fully support ipv6. 

The workaround to this is rather simple.

> Changing "localhost" to "127.0.0.1" should avoid this

The default url parameter in mongo is currently localhost, that his how I ran into this problem while testing something locally. Probably you should consider changing the default setting to ipv4 style or add a line in the documentation.

**Comment by jeroenooms** [comment]
OK https://github.com/jeroenooms/mongolite/commit/30ea60d2f0e1629be8e7b53a7e7b3d14a75ce455
