### ISSUE TITLE
Insert JSON into mongodb with list of dates

### ISSUE THREAD

**Issue by MattChen37** [jeroenooms/mongolite#57]
Hi,

 I have a question about using mongolite to insert JSON into mongodb containing a list of dates.

When I insert one date, the code I use is like this:
{"mydate":{"$date":"2016-10-11T00:00:00Z"}}
and is works perfectly. 

When I need to insert two dates in a list to the same "mydate" field, I use code like this:
{"mydate":[{"$date":"2016-10-11T00:00:00Z"},{"$date":"2016-10-12T00:00:00Z"}]}

It can still insert the record into DB but from Robomongo it has 4 elements and the document looks like following:
{
    "_id" : ObjectId("57fc0a1884d9531450001592"),
    "mydate" : [ 
        undefined, 
        ISODate("2016-10-11T00:00:00.000Z"), 
        undefined, 
        ISODate("2016-10-12T00:00:00.000Z")
    ]
}

Is there anything I did wrong? What I want is "mydate" field containing 2 date elements without the "undefined". 

Thanks,
Matt

**Comment by jeroenooms** [comment]
Problem with date simplification:

```r
library(mongolite)
m <- mongo()
m$insert('{"mydate":[{"$date":"2016-10-11T00:00:00Z"},{"$date":"2016-10-12T00:00:00Z"}]}')
x <- m$find()
x$mydate
```

**Comment by MattChen37** [comment]
Thanks Jeroen.
