### ISSUE TITLE
how to find data with an objectId

### ISSUE THREAD

**Issue by ChanningWong** [jeroenooms/mongolite#58]
I want to find data with an objectId, 
         m$find('{"_id":ObjectId("55efa63dab7271151dfd3c00")}'
but got a error with 
         "Error: Invalid JSON object: {"_id":ObjectId("55efa63dab7271151dfd3c00")}"
Is there any way to approach that?

**Comment by ChanningWong** [comment]
I've found the answer:
m$find('{"_id":{"$oid":"55efa63dab7271151dfd3c00"}}'')

**Comment by jeroenooms** [comment]
This is also described in the new docs: https://jeroenooms.github.io/mongolite/query-data.html#select-by-id

**Comment by FlorianSchwendinger** [comment]
For completeness, for multiple ids one needs to use "$in" which can be constructed by something like this.
```r
query_uid <- function(oid) {
    stopifnot(is.character(oid), !anyNA(oid), length(oid) > 0L)
    if (length(x) == 1L) {
        q <- list("_id" = list("$oid" = oid))
    } else {
        q <- list("_id" = list("$in" = lapply(oid, function(x) list("$oid" = x))))
    }
    jsonlite::toJSON(q, auto_unbox = TRUE, pretty = FALSE)
}

db$find(query = query_uid("62021ea8be54b330ed3c67d6"))
db$find(query = query_uid(c("62021ea8be54b330ed3c67d5", "62021ea8be54b330ed3c67d6")))
```
