### ISSUE TITLE
is it possible to disable simplifying to data frame?

### ISSUE THREAD

**Issue by FrissAnalytics** [jeroenooms/mongolite#60]
Hi,

is it possible to have mongolite return a list of lists or just JSON, instead of always simplifying to a data frame ? In other words, would it be possible to have a bit more control over how mongolite returns a query, similar to what you can do with jsonlite with its simplification options?

As noted in #37 simplifying can sometimes be slow. Also, sometimes simplifying leads to quite large, sparse objects, with many NAs. In those cases it may be convenient to use either jsonlite to force a different type of formatting or to use e.g. [rlist](https://github.com/renkun-ken/rlist) to extract information from a nested list.

**Comment by ericwatt** [comment]
Try using `m$iterate()$batch()` instead of `m$find()`.

http://stackoverflow.com/questions/39673647/r-mongolite-arrays-are-loaded-from-mongo-as-columns-with-elements-as-data-frame/39683181#39683181

**Comment by FrissAnalytics** [comment]
works like a charm! sorry for the late reply...
