### ISSUE TITLE
NodeJS translation... nested findOne using object IDs

### ISSUE THREAD

**Issue by FredericS2018** [jeroenooms/mongolite#66]
Wasn't sure whether to ask this here or on SO. 

I am trying to translate the following NodeJS code to mongolite:

```js
function getNotes(done) {
  noteSchema.find({}).exec((err, notes) => {
    var numNotes = 0;
    async.each(notes, (n, next) => {
		userSchema.findById(n.userId, (err, user) => {
        if (err || !user) { next(); return; }
        var emailsStr = utils.getEmailsString(user.emails);
            if (!utils.toSkipEmail(emailsStr)) {
				//console.log('test 1')
					meetingSchema.findById(n.meetingId, function (err, meeting) {
					if (meeting.name.displayValue.indexOf('test', 'Test') == -1) {
						numNotes++;
					}
					next();
					//console.log('test 2')
				});
			} else {
			//console.log('test3')
			next(); 
			}
		})
    }, (err, result) => {
      console.log(util.format('Total Number of Notes: %d', numNotes));
      done(null);
    });
  });
}
```
What would be the suggested approach? I am attempting to build cursors with $iterate, but then using the cursors in an each loop or if else statement to $iterate through another collection it becomes quite difficult because of the additional cursor created for the next collection. Maybe also because the each loop is async.

**Comment by jeroenooms** [comment]
I'm not quite sure what exactly is the question, but R does not support async or threading. It's perfectly fine to have multiple cursors nested inside one another when using the `iterate()` method.

If this is still a problem, can you help me by creating a new issue with a minimal example and some example data?
