### ISSUE TITLE
$slice doesn't work?

### ISSUE THREAD

**Issue by estaub** [jeroenooms/mongolite#67]
I can't guess why this would be, but AFAICT the $slice projection operator doesn't work in mongolite.  Example:

`conStates$find('{}','{"id":1,"terms":{"$slice":1},"_id":0,"chambers":1}')`

The same parameters work fine in, e.g. mongodb shell.

**Comment by jeroenooms** [comment]
Can you maybe provide some example data for me to reproduce this problem?

**Comment by estaub** [comment]
@jeroenooms Sorry, it's been too long, I'm not even using Mongo anymore.
