### ISSUE TITLE
Using $or operator on key value pair in mongolite

### ISSUE THREAD

**Issue by SyedAgha** [jeroenooms/mongolite#68]
Hi,

I am using "$or" operator on a key value pair. But unfortunately I get no records. Here is my query.

```js
{ "$or":[{"p.categ.123":{"$exists":true}}, {"p.catsc.456":{"$exists":true}} ]}
```

Below is the structure of my collection: 
```
"p": {
          "categ" : {          
                    "123":1,
                    "456":1,
                    "789":1
                  }
}
```
An examination of the data shows that there are records that satisfy these conditions. Can anyone please tell me how to rectify this problem?

Best,
Agha

**Comment by jeroenooms** [comment]
The `$or` operator seems to work fine for me, for example:

```r
m <- mongo("diamonds")
m$insert(ggplot2::diamonds)
mydata <- m$find('{"$or": [ {"cut" : "Ideal"}, {"cut" : "Premium"}  ]}')
mydata$cut
```

I also tried with your example data and it seems to work here. Maybe your server version is too old?
