### ISSUE TITLE
Trying to find by id... bad parse, but valid JSON?

### ISSUE THREAD

**Issue by FredericS2018** [jeroenooms/mongolite#69]
Here is a simple for loop:

```
for (n in noted$meetingId) {
  meetings$find('{"_id": {"$oid": "n"}}')
}
```

I am looking to return meetings which match the find query. The query works when using an individual meeting._Id (objectId) for n, but not when looping the n's through noted$meetingId, which is a vector of meeting._Id 's.

I get the error 'Invalid input string n, looking for 2'

**Comment by SyedAgha** [comment]
for (n in noted$meetingId) {
  meetings$find('{"_id": {"$oid": "n"}}')
}
The problem is that it takes "n" as a string. You have to add something extra to make it work. 

Try this:
for (n in noted$meetingId) {
  meetings$find(paste0('{"_id": {"$oid":' , n, '}}')
}

**Comment by FredBastiat** [comment]
Thank you! that got me farther along. Now I'm stuck with an invalid JSON object error using your code for some reason. Not sure why; it should be a valid objectId

**Comment by SyedAgha** [comment]
Since I don't know the actual problem; however, you can fix it up using following lines
library(jsonlite)

for (n in noted$meetingId) {
meetings$find(paste0('{"_id": {"$oid":' , toJson(n), '}}')
}

**Comment by FredBastiat** [comment]
Now I'm getting Error in check_col() : could not find function "null_ptr" 

How come n is a null pointer? Should I not be using a for loop? I ran a find query to get the noted dataframe, which contains a meetingId column. Having trouble diagnosing this. Thank you for your help once again.
