### ISSUE TITLE
Creation of ObjectId

### ISSUE THREAD

**Issue by pmoulos** [jeroenooms/mongolite#72]
Hello,

Thanks for the wonderful work. I would like to ask (and/or feature request if not already possible), if there is a way to create a new Mongo ```ObjectId``` with ```mongolite```. Whatever I tried with ```$oid``` and ```jsonlite::toJSON()``` just converts it to text. For example: 
```
id <- "eb34c5a2dd617c39a8555288"
x <- list(_id=paste0("{$oid: '",id,"'}"))
```
creates
```
{"analysis_id":"{$oid: 'eb34c5a2dd617c39a8555288'}"}
```
which is a string when imported to MongoDB. 
```
{
    "analysis_id" : "{$oid: 'eb34c5a2dd617c39a8555288'}"
}
```

I tried several tunings of ```jsonlite::toJSON()``` like playing with ```raw="mongo"``` and ```force=TRUE``` without success. 

The reason for which I would like such a feature is to embed ```ObjectId```'s referring to documents in other collections.

Thanks!

**Comment by jeroenooms** [comment]
You mean something like this?

```r
library(jsonlite)
id <- "eb34c5a2dd617c39a8555288"
toJSON(list("_id" = list("$oid" = unbox(id))))
```
```
{"_id":{"$oid":"eb34c5a2dd617c39a8555288"}} 
```
