### ISSUE TITLE
Use a variable in $iterate

### ISSUE THREAD

**Issue by Mozasf** [jeroenooms/mongolite#74]
Hi everyone!

I would like to know if It´s possible to use a var with the function $iterate?
I have a code like this:

```
iter <-  mongo$iterate('{"Date":{"$gt":1483228800}}')
i<-1
while(!is.null(Fecha <- iter$one())){
	j<-1
	n <- length(Fecha$clients)
    	while(j<n+1){
    		Date[i] <- Fecha$Date
    		....
		j=j+1
		i=i+1
	}
}
```
And I would like to pass a var (for example: d<-as.numeric(as.POSIXct(floor_date(today(),"month")))) instead of a number in this part.
iter <-  mongo$iterate('{"Date":{"$gt":1483228800}}')

Thanks!

**Comment by jeroenooms** [comment]
Is your question on how to generate a json string? Try looking into `jsonlite::toJSON`, for example:

```r
var <- 1483228800
jsonlite::toJSON(list(Date = list("$gt" = var)), auto_unbox = TRUE)
## {"Date":{"$gt":1483228800}} 
```
