### ISSUE TITLE
iterate()$batch() returns timestamp as integer

### ISSUE THREAD

**Issue by petroswork** [jeroenooms/mongolite#75]
If I use:
```
mongo_con$iterate(paste0('{ "key":' , toJSON(unbox("key")), '}'), fields='{}')$batch()
```
the list returned has a data frame with a timestamp (ISODate), which appears as an integer (the timestamp column is ``createdAt$`$date` ``). One way to restore the timestamp data type is to use:
```
jsonlite:::simplify(mongo_con$iterate(paste0('{ "key":' , toJSON(unbox("key")), '}'), fields='{}')$batch(), simplifyDataFrame=FALSE)
```

**Comment by 1beb** [comment]
I use this to convert to a date: 

```
as.POSIXct(createdAt$`$date`/1000,origin = "1970-01-01")
```

**Comment by jeroenooms** [comment]
Duplicated of https://github.com/jeroenooms/mongolite/issues/81.
