### ISSUE TITLE
Rounding error for number long

### ISSUE THREAD

**Issue by fredheir** [jeroenooms/mongolite#77]
Long numbers occasionally are incorrectly rounded on import. Suspect this may be caused by jsonlite and digits. For instance
819980654209363970
is handled as
819980654209363968

See:

`> options("scipen"=999,digits=22)
> q='{"_id":819980654209363970}'
> m = mongo(collection = 'searchResults', db = 'temp', url = "mongodb://localhost") 
> m$find(q,fields='{"_id":1}')
 Imported 1 records. Simplifying into dataframe...
                 _id
1 819980654209363968`

**Comment by jeroenooms** [comment]
Why are you using integers as `_id`? This problem does not appear if you use the default Mongo `oid` type. R only supports `double` numbers so the rounding error is expected.

Note that similar rounding error happens when the JSON string is parsed in JavaScript:

```js
~ var x = {"_id":819980654209363970}
~ x._id
819980654209364000
```

**Comment by fredheir** [comment]
It's hard to prevent duplicate entries using oid. I understand the problem and why using a text string makes sense. But in the abstract I don't think the sfotware should restrict design decisions in this way.

I note that parseJSON from jsonlite has a bigint_as_char option that handles this situation nicely. Could that be copied across?

`
> jsonlite:::parseJSON
function (txt, bigint_as_char = FALSE) 
{
    if (inherits(txt, "connection")) {
        parse_con(txt, 1024^2, bigint_as_char)
    }
    else {
        parse_string(txt, bigint_as_char)
    }
}
<environment: namespace:jsonlite>
`

**Comment by jeroenooms** [comment]
Yeah I guess we could add something like that.

**Comment by jeroenooms** [comment]
The development version now has an option to set this:

```r
devtools::install_github("jeroenooms/mongolite")
```

And then to enable this you set:

```r
mongo_options(bigint_as_char = TRUE)
```
