### ISSUE TITLE
find() does not add UTC time zone to ISODate objects

### ISSUE THREAD

**Issue by egnha** [jeroenooms/mongolite#79]
Is this expected behavior (if so, why?), or a bug?

Minimal example:

```R
library(mongolite)

x <- as.POSIXct("2017-01-01", origin = "1970-01-01", tz = "UTC")

# Insert x (into local instance)
cnx <- mongo(collection = "test_dtm")
if (cnx$count() != 0L) cnx$drop()
cnx$insert(data.frame(x = x), POSIXt = "mongo")

# Recover x
x_fetch <- cnx$find()$x

# Equal but not identical ...
all.equal(x, x_fetch)  # TRUE
identical(x, x_fetch)  # FALSE

# ... because time zones differ
is_utc <- function(.) identical(attr(., "tzone"), "UTC")
sapply(list(x, x_fetch), is_utc)  # TRUE FALSE
```

These results were produced under the following setup:

```R
sessionInfo()
#> R version 3.3.0 (2016-05-03)
#> Platform: x86_64-apple-darwin14.5.0 (64-bit)
#> Running under: OS X 10.11.5 (El Capitan)
#> 
#> locale:
#> [1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base
#> 
#> other attached packages:
#> [1] mongolite_0.9.1
#> 
#> loaded via a namespace (and not attached):
#> [1] jsonlite_1.2
```

**Comment by ajdavis** [comment]
Perhaps this works as designed? MongoDB itself does not store dates with timezones:

https://docs.mongodb.com/v3.2/tutorial/model-time-data/

So, mongolite could assume all datetimes it retrieves are UTC, but that assumption might be dangerous.

A full implementation could emulate PyMongo, which autoconverts local times to UTC before inserting, and adds the UTC timezone to dates it retrieves.

http://api.mongodb.com/python/current/examples/datetimes.html

**Comment by egnha** [comment]
Since retrieved date-time objects are UTC, wouldn't it be natural to impose that structure explicitly, by auto-adding UTC by default? (Like PyMongo.) I don't see how that would be dangerous (other than possibly breaking code that currently requires monogolite-retrieved date-time objects *not* to have any `tzone` attribute set). Am I overlooking something?

**Comment by ajdavis** [comment]
I guess it's not dangerous, really. I'm speaking from an old memory when people would store local times in MongoDB (without any explicit timezone) and want to retrieve them without converting to UTC. If Mongolite users are handling timezones correctly before they insert times into MongoDB, then automatically marking times as UTC when retrieving data will work fine.

**Comment by jeroenooms** [comment]
MongoDB does not distinguish between a local datetime and universal datetime, as R does. Therefore if you roundtrip dates, they get coerced to UTC times. However the epoch time is still the same:

```r
> unclass(x)
[1] 1483228800
attr(,"tzone")
[1] "UTC"

> unclass(x_fetch)
[1] 1483228800
```

I don't think there is a better solution here. There is no way for R to know if the datetime you get from MongoDB should be presented in UTC or local form...

**Comment by egnha** [comment]
@jeroenooms As you note, MongoDB does in fact assume that date-times are UTC, so that is what the mongolite user will expect. But `find()` in its current implementation does not abide by that assumption, leading to surprises; `x` and `x_fetch` will not be coerced to the same POSIXlt object, so you'll get different local hour. (That MongoDB only knows UTC is more of a cautionary issue for users when `insert()`'ing, since the burden is then on the user to ensure that date-times written to MongoDB reflect UTC.)

**Comment by jeroenooms** [comment]
If mongolite would always interpret datetime objects as `UTC`, then the exact opposite problem would appear. 

In your example this would solve the problem because your original `x` has `tzone = "UTC"`. However far more often, dates do not have an explicit timezone attribute and are interpreted as local time. If we `mongolite` would mark everything as `UTC`, this would throw off users who insert some local times and then get back (seemingly different) times in UTC.

**Comment by egnha** [comment]
There is still the problem that `x` and `x_fetch` are not identical, whenever `x` has a time zone—local or whatever, doesn't matter which, because `x_fetch` has no `"tzone"` attribute whatsoever. If the typical situation is to insert a date time object with a local time zone, then, if I'm not mistaken, the `"tzone"` attribute is `""`, not `NULL`.

I don't see why maintaining round-trip local time consistency is compelling. Generally, there is no connection between local time zone at insertion and local time zone at retrieval. Moreover, MongoDB only knows UTC.

In any case, this is up to you. But I think the current behavior is a confusing inconsistency (not just for me) in an otherwise great package.

**Comment by jeroenooms** [comment]
The default interpretation of a datetime in R is with `tzone == NULL`, i.e local time:

```r
now <- Sys.time()
print(now)
## "2017-02-27 19:00:32 CET"
attributes(now)
## $class
## [1] "POSIXct" "POSIXt" 
```

Note that `now` does not have a `tzone` attribute, but that the value of the epoch matches that in the extjson (and hence mongodb), even though my timezone is not UTC:

```r
unclass(now)
## 1488218009
json <- jsonlite::toJSON(now, POSIXt = 'mongo')
print(json)
## [{"$date":1488218008776}]
```

Now the only arbitrary thing is if this epoch value should be presented to the R user in UTC or local time. The default behavior in R is to turn it back into local time:

```r
value <- jsonlite::fromJSON(json)
print(value)
## "2017-02-27 18:53:28 CET"
```

So we get back the local time from `now` above. For other cases you might want to mark the time as UTC. This will not change the actual epoch time, only which timezone is used to print local time:

```r
> attr(value, "tzone") = "UTC"
> value
[1] "2017-02-27 17:53:28 UTC"
```

I don't think one is better than the other, but in the absence of an explicit timezone in Mongo, I think we should follow R's default behavior which is to show timestamps in local time.

**Comment by egnha** [comment]
That makes sense, thanks for your careful explanation.

Confusingly, it seems that sometimes `NULL` stands for the current time zone, and sometimes the empty string does, and it's not predictable when:
```R
attributes(as.POSIXct(Sys.time()))
#> $class
#> [1] "POSIXct" "POSIXt" 

attributes(as.POSIXct("2017-01-01"))
#> $class
#> [1] "POSIXct" "POSIXt" 
#> 
#> $tzone
#> [1] ""
```
(According to `?as.POSIXct`, `""` stands for the local time zone.)

Given this mess, do you think it would be helpful to add some clarification about the handling of time zones in the mongolite docs? (The new release would be a good opportunity for that ... )
