### ISSUE TITLE
Get ID of inserted records

### ISSUE THREAD

**Issue by jeroenooms** [jeroenooms/mongolite#80]
A recurring feature request is to have the `insert()` method return the `id`'s of the inserted records. Is somthing like this possible with `mongoc_collection_insert` or `mongoc_collection_insert_bulk` ? @ajdavis

**Comment by ajdavis** [comment]
Hi, it's a bit inconvenient: you must generate the id's yourself when you create the documents. Or, if the documents are produced by user code, you must add the id's before calling mongoc_collection_insert, that way you know what the id's are and you can return them to the caller.

This is documented here:

http://mongoc.org/libmongoc/current/mongoc_collection_insert.html#description

**Comment by jeroenooms** [comment]
Right, but there is no way to specifically get the auto-generated ID's from inserted records?

**Comment by ajdavis** [comment]
Right.

**Comment by AndreGuerra123** [comment]
I think it is highly needed.
