### ISSUE TITLE
add support for sql through slamengine

### ISSUE THREAD

**Issue by jdegoes** [jeroenooms/mongolite#9]
The [slamengine](http://github.com/slamdata/slamengine) project could be used to add SQL support to this library so it's possible to query MongoDB from R using SQL syntax.

**Comment by jeroenooms** [comment]
This would better be suited as a separate package that depends on `mongolite`. I don't want to introduce a Java dependency in mongolite itself, but you are free to create an R package `slamengine` that builds on monoglite and rJava to do mongo SQL queries in R.
